name: Caching Exercise
on: [push]

jobs:
  cache-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Cache
        id: cache-step
        uses: actions/cache@v4
        with:
          path: my-cache-dir
          key: cache-820d9fa

      - name: prime-cache-820d9fa
        run: |
          echo "Cache hit result: ${{ steps.cache-step.outputs.cache-hit }}"
          if [ "${{ steps.cache-step.outputs.cache-hit }}" != "true" ]; then
            mkdir -p my-cache-dir
            echo "Priming the cache..." > my-cache-dir/data.txt
          fi